os: linux
dist: bionic
# Python is required to run `doc_status.py`.
language: python

python:
  - 3.8

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.65.3/hugo_0.65.3_Linux-64bit.tar.gz
  - tar xf hugo_0.65.3_Linux-64bit.tar.gz hugo
  - sudo mv hugo /usr/local/bin/

script:
  - ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  token: $GITHUB_TOKEN

  # Deploy to an organization repository's `master` branch to benefit from
  # a shorter, prettier URL.
  target_branch: gh-pages

  # Only deploy from the `master` branch.
  on:
    branch: master
